### ISSUE TITLE
CRAN checks fail when building vignettes

### ISSUE THREAD

**Issue by brianstock** [xfim/ggmcmc#72]
Hello,

I've used `ggmcmc` to output diagnostics in a package ([MixSIAR](https://github.com/brianstock/MixSIAR)), and received the following email from CRAN. Are you planning on keeping `ggmcmc` on CRAN? If not, it would be nice to know before 2021-02-12 so I can remove the `ggmcmc` dependency from `MixSIAR`.

Thanks,
Brian

-----------------------------------------------------------------------------

This concerns the CRAN packages

  BayesMallows MixSIAR PLMIX ggmcmc missingHE

maintained by one of you:

  Andrea Gabrio <ucakgab@ucl.ac.uk>: missingHE
  Brian Stock <bstock09@gmail.com>: MixSIAR
  Cristina Mollica <cristina.mollica@uniroma1.it>: PLMIX
  Oystein Sorensen <oystein.sorensen.1985@gmail.com>: BayesMallows
  Xavier Fernández i Marín <xavier.fim@gmail.com>: ggmcmc

We have asked for an update fixing the check problems shown at
  <https://cran.r-project.org/web/checks/check_results_ggmcmc.html>
with no update from the maintainer thus far.

Thus, package ggmcmc is now scheduled for archival on 2021-02-12, and
archiving this will necessitate also archiving its strong reverse
dependencies.

Please negotiate the necessary actions.

-----------------------------------------------------------------------------

It seems the warnings/errors are thrown when building `v70i09.Rnw`, possibly with the use of `data_frame()` and/or `cairo_pdf()`.

```
Warning: `data_frame()` is deprecated as of tibble 1.1.0.
    Please use `tibble()` instead.
```

But from your last commit message it seems like you're already aware of this...

```
Error: processing vignette 'v70i09.Rnw' failed with diagnostics:
    Running ‘texi2dvi’ on ‘v70i09.tex’ failed.
    LaTeX errors:
    ! Undefined control sequence.
    <recently read> \Hy@colorlink
    
    l.109 \begin{document}
    
    ! Undefined control sequence.
    \close@pdflink ->\Hy@endcolorlink
     \Hy@VerboseLinkStop \pdfendlink 
```

```
--- re-building ‘v70i09.Rnw’ using knitr
Warning: The device 'cairo_pdf' is not operational; falling back to 'pdf'.
```

**Comment by xfim** [comment]
Yes, yes of course @brianstock . I am working on it.

**Comment by xfim** [comment]
Done. Sorry @brianstock it took a while, for a really minimal change. But knowing where it was the key, and also adapting to the new requirements of the M1mac architecture. 

Thank you for your support.

ggmcmc-1.5.1.1 is in CRAN.

**Comment by brianstock** [comment]
Great news! Thanks for handling this. I know the maintenance takes a frustrating amount of time... MixSIAR got booted from CRAN briefly in the past because I didn't fix a minor issue soon enough.
